### ISSUE TITLE
byte[] to file

### ISSUE THREAD

**Issue by v2mgm** [irasuna/pes16converter#1]
### I use the following code to get the file but file is not opening By other editing software (like: PES Next-Gen Editor 0.6.5).

> PS3 to PC

`byte[] arrXBOX = Converter.ps3ToXbox("e:/DATA");`
`File.WriteAllBytes("e:/pc", arrXBOX);`
`byte[] arrPC = Converter.xboxToPc("e:/pc");`
`File.WriteAllBytes("e:/pc", arrPC);`

**thanks for pes16converter repository. :)**

**Comment by irasuna** [comment]
First of all, please read the [README.md](../blob/master/README.md) carefully. It is stated under Getting Started,

> ... where `filePath` refers to a full directory path of the file that is **going to be converted**.

So I assume `DATA` is the PS 3 Option File, not a folder.

Second of all, in C# there is two way of specifying file path,
```C#
string myFileName = "C:\\Documents and Settings\\user\\Desktop\\xxx.txt";

or

string myFileName = @"C:\Documents and Settings\user\Desktop\xxx.txt";
```

So instead of `"e:/DATA"` and `"e:/PC"`, it should be `@"e:\DATA"` and `@"e:\PC"`

Lastly, in the end, PC option file that is generated from the conversion of XBOX or PS3 will only resulting in the internal Option File part known as data.dat. Please refer to my post on [evo-web.co.uk](https://www.evo-web.co.uk/threads/pes-2016-converter.76282/#post-3129632)

> The last and the most important thing to know is, as we all might have noticed that this year, the option file is divided into 6 part, and one of them is "data.dat", at least that's what tunabrain (the origin of the pes16decrypter owner) called that portion of the file. And the more interesting part is that the option file saved in XBOX is only that "data.dat" part in the PC. So if you are converting the option file from XBOX to PC, you are actually just converting that "data.dat" part only. So in order for you to be able to use it properly in PC, you need to somehow port/inject that "data.dat" that is converted from XBOX, to a PC option file, so that you can use it in any kind of third-party editors in PC. And so does the other way. If you are going to convert from PC to XBOX, you are not suppose to convert the whole option file! You need to somehow, export the "data.dat" part only from the option file, or if it is already in that "data.dat" format then you are good to go. This is very important to know for developers that might want to use the library.



Best Regard,
Rasuna
